### ISSUE TITLE
AK1001 CodeFix bugs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.analyzers#59]
Thanks for the explanation @Aaronontheweb. But I've one follow up question regarding this topic.

> Also @wesselkranenborg, you code is fine - minus the bit I said about the perf hit using `ReceiveAsync` instead of `Receive` when you're not performing any `await`s.

Basically we are now writing non-blocking code if I hear you correctly. And we might thus break the actor model?
I've three examples on how we could write this:
<img width="550" alt="image" src="https://github.com/akkadotnet/akka.analyzers/assets/4964604/96d4377e-563c-4688-b4b6-12d0b085469d">

In this example we have the `LeaveClusterCore` async method which is awaiting code. We want this method to be executed and freeing up the actor once this logic is performed. We are now using the first method, the second method is to make it with the Receive<> but if I hear you correctly we should use the last way of writing it. Am I correct on that?

_Originally posted by @wesselkranenborg in https://github.com/akkadotnet/akka.analyzers/issues/55#issuecomment-1897948812_

**Comment by Aaronontheweb** [comment]
From me on #55 

> Thanks for the answers
> 
> > Your second example is fine and should not be flagged by AK1001 (is it being flagged currently?)
> 
>
> Yes, it is.

**Comment by Arkatufus** [comment]
Question, why is this code safe?
```csharp
this.Receive<Message>(s ==> MessageHandler(s).PipeTo(this.Sender));
```

**Comment by Aaronontheweb** [comment]
> Question, why is this code safe?
> 
> ```cs
> this.Receive<Message>(s ==> MessageHandler(s).PipeTo(this.Sender));
> ```

Ah, is `MessageHandler` returning a `Task` ? If so it's not safe and the analyzer is right, so we could close this issue.  @akkadotnet/ci-admins

**Comment by Aaronontheweb** [comment]
whoops, meant to tag you @Arkatufus

**Comment by Arkatufus** [comment]
Judging by the context of the other code fragments, `LeaveClusterCore()` does return a `Task`.

**Comment by Aaronontheweb** [comment]
My mistake then.
