### ISSUE TITLE
AK1000 Must close over `Sender` and `Self` when accessed inside a lambda argument body

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/akka.analyzers#71]
`Sender`, `Self`, `Context.Sender` and `Context.Self` must be closed when accessed inside a lambda expression argument body, because it can go out of context.

**Comment by Aaronontheweb** [comment]
I think we need a live code reproduction of this bug before we write an analyzer rule for it, lest we have the `PipeTo` problem.

**Comment by Arkatufus** [comment]
The relevant repro for this edge case is here: https://github.com/akkadotnet/akka.net/pull/7122

**Comment by Aaronontheweb** [comment]
@Arkatufus looks legit - please proceed with writing the rules and fixes
